import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { fromImageToUrl, API_URL } from '../utils/urls'
import { twoDecimals } from '../utils/format'
import React, { useState, useEffect } from 'react';
import axios from 'axios'

import {useRouter} from 'next/router'
import {Flex, Box} from 'reflexbox'
import PictureList from '../components/PictureList'
import Pagination from '../components/Pagination'


export default function Home({ products, page }) {
  const router = useRouter()
  console.log(router.query)

  const [ items, setItems] = useState([]);
  const [loading, setLoading] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [itemPerPage, setItemPerPage] = useState(3);

  useEffect( ()=>{
    const fetchItem = async () => {
      setLoading(true);
      const res = await axios.get('https://api.unsplash.com/photos/?client_id=cqlsSGNsAAPgh0e8I_-RMm8vdJicidXIJkIEw1ifRH8');
      setItems(res.data);
      setLoading(false);
    }
    fetchItem();
  }, []);

  console.log(items);

  const indexOfLastItem = currentPage  * itemPerPage;
  const indexOfFirstItem = indexOfLastItem - itemPerPage;
  const currentItems = items.slice(indexOfFirstItem, indexOfLastItem);
  
  // Change page
  const paginate = (pageNumber) => setCurrentPage(pageNumber);

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Box variant="container" pt={0}>
      
      
      <PictureList items={currentItems} loading={loading} />
      

      <Flex>
      <Pagination itemPerPage={itemPerPage} totalItems={items.length} paginate={paginate} />
      </Flex>

      </Box>

    </div>
    
    
  )
}
